name: Sync Files from Another Repo

on:
  schedule:
    - cron: '0 0 * * *'  # 每天執行一次
  workflow_dispatch:  # 也可以手動觸發

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.token }}

      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          repository: fangnina666/stock_legal_info  # 來源 repository
          path: stock_legal_info
          token: ${{ secrets.token  }}

      - name: Copy MD files only
        run: |
        
          # 只複製 .md 檔案
          find stock_legal_info/reports -name "*.md" -exec cp {} ./reports/ \;
          
          # 或者如果想保留原本的目錄結構
          # find source-repo/reports -name "*.md" -exec bash -c 'mkdir -p "./reports/$(dirname "{}" | sed "s|source-repo/reports||")" && cp "{}" "./reports/$(echo "{}" | sed "s|source-repo/reports||")"' \;

      - name: Commit and push if changed
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Sync files from source repo" && git push)
