name: Sync Files from Another Repo

on:
  schedule:
    - cron: '0 0 * * *'  # 每天執行一次
  workflow_dispatch:  # 也可以手動觸發

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.token }}

      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          repository: fangnina666/stock_legal_info  # 來源 repository
          path: stock_legal_info
          token: ${{ secrets.token  }}

      - name: Copy MD files only
        run: |
        
          mkdir -p ./reports_his # 建立目標資料夾
        
          # 只複製 .md 檔案
          find stock_legal_info/reports_his -name "*.md" -exec cp {} ./reports_his/ \;
          rm -rf stock_legal_info
          # 或者如果想保留原本的目錄結構
          # find source-repo/reports -name "*.md" -exec bash -c 'mkdir -p "./reports/$(dirname "{}" | sed "s|source-repo/reports||")" && cp "{}" "./reports/$(echo "{}" | sed "s|source-repo/reports||")"' \;

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add reports_his/
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: sync MD files from stock_legal_info at $(date -u +'%Y-%m-%d %H:%M:%S') UTC"
            git push
          fi
